[build]
  command = "npm run build"

[context.production]
  environment = { NODE_VERSION = "18.9.0", NETLIFY_BUILD_DEBUG = true }

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"